# Generated by Django 5.0.4 on 2024-05-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('difficulty_level', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficultylevel',
            options={'ordering': ['name'], 'verbose_name': 'Nivel de dificultad', 'verbose_name_plural': 'Niveles de dificultad'},
        ),
    ]
