# Generated by Django 5.0.4 on 2024-05-09 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dificulty_level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exercise.difficultylevel')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercises', to='exercise.exercisetype')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='muscle_groups', to='exercise.exercise')),
                ('muscle_exercise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exercise.muscleexercise')),
            ],
        ),
    ]
