name: ${CONTAINER_NAME:?container name is not defined...}-django
services: 
  dev: 
    container_name: ${CONTAINER_NAME:?container name is not defined...}-dev
    build: 
      context: . 
      dockerfile: ./docker/dev.Dockerfile
      target: final
    env_file:
      - ./.env
    environment:
      - TZ=America/Argentina/Buenos_Aires
    restart: always
    ports:
      - ${APP_PORT:-8000}:8000
    volumes:
      - ./src:/app:rw
    extra_hosts:
      - host.docker.internal:host-gateway
