# Generated by Django 5.0.4 on 2024-05-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutine_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutinetype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de rutina', 'verbose_name_plural': 'Tipos de rutina'},
        ),
    ]
