# Generated by Django 5.0.4 on 2024-05-24 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difficulty_level', '0001_initial'),
        ('exercise', '0001_initial'),
        ('exercise_type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='dificulty_level_id',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='user_id',
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty_level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='difficulty_level.difficultylevel'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='exercise_type.exercisetype'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='exercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
