# Generated by Django 5.0.4 on 2024-05-22 23:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rutine', '0001_initial'),
        ('rutine', '0004_rutine_user_rutine_alter_rutine_user'),
        ('trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssingRutine',
            new_name='AssignRutine',
        ),
        migrations.AlterModelOptions(
            name='assignrutine',
            options={'ordering': ['user'], 'verbose_name': 'Rutina asignada', 'verbose_name_plural': 'Rutinas asignadas'},
        ),
        migrations.RenameField(
            model_name='assignrutine',
            old_name='rutine_id',
            new_name='rutine',
        ),
        migrations.RenameField(
            model_name='assignrutine',
            old_name='trainer_id',
            new_name='trainer',
        ),
        migrations.RenameField(
            model_name='assignrutine',
            old_name='user_id',
            new_name='user',
        ),
    ]
