from .list_view import DifficultyLevelListView
from .detail_view import DifficultyLevelDetailView
from .create_view import DifficultyLevelCreateView
from .update_view import DificultyLevelUpdateView
from .delete_view import DifficultyLevelDeleteView
