# Generated by Django 5.0.4 on 2024-05-27 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trainers',
            field=models.ManyToManyField(related_name='user_trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
