# Generated by Django 5.0.4 on 2024-05-27 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_trainers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trainers',
        ),
    ]
