# Generated by Django 5.0.4 on 2024-05-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muscle_exercise', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MuscleExercise',
        ),
    ]
