# Generated by Django 5.0.4 on 2024-05-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muscle_exercise', '0002_delete_muscleexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ejercicio de musculo',
                'verbose_name_plural': 'ejercicios de musculos',
                'ordering': ['name'],
            },
        ),
    ]
