<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-29 22:11

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.0.4 on 2024-05-29 16:08

import django.db.models.deletion
>>>>>>> 4a5de682cea77da36cf37dad67566ec6a859f725
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('exercise', '0002_remove_exercise_dificulty_level_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('exercise', '0001_initial'),
>>>>>>> 4a5de682cea77da36cf37dad67566ec6a859f725
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exercise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exercise.exercise')),
<<<<<<< HEAD
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> 4a5de682cea77da36cf37dad67566ec6a859f725
            ],
        ),
    ]
