# Generated by Django 5.0.4 on 2024-05-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='user_id',
            new_name='user',
        ),
    ]
