# Generated by Django 5.0.4 on 2024-05-27 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_alter_trainer_is_verify_alter_trainer_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='users',
            field=models.ManyToManyField(related_name='user_trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
