# Generated by Django 5.0.4 on 2024-05-12 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        ('rutine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exercise.exercise')),
                ('rutine_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rutine.rutine')),
            ],
        ),
    ]
