# Generated by Django 5.0.4 on 2024-05-17 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difficulty_level', '0001_initial'),
        ('rutine', '0001_initial'),
        ('rutine_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutine',
            options={'ordering': ['name'], 'verbose_name': 'Rutina', 'verbose_name_plural': 'Rutinas'},
        ),
        migrations.RenameField(
            model_name='rutine',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='rutine',
            name='difficulty_level_id',
        ),
        migrations.RemoveField(
            model_name='rutine',
            name='rutine_type_id',
        ),
        migrations.AddField(
            model_name='rutine',
            name='difficulty_level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='difficulty_level.difficultylevel'),
        ),
        migrations.AddField(
            model_name='rutine',
            name='rutine_type',
            field=models.ManyToManyField(to='rutine_type.rutinetype'),
        ),
    ]
