# Generated by Django 5.0.4 on 2024-05-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
        ('rutine', '0002_alter_rutine_options_rename_user_id_rutine_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutine',
            name='rutine_exercises',
            field=models.ManyToManyField(to='exercise.exercise'),
        ),
    ]
