# Generated by Django 5.0.4 on 2024-05-20 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutine', '0003_rutine_rutine_exercises'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rutine',
            name='user_rutine',
            field=models.ManyToManyField(related_name='user_rutines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rutine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rutines', to=settings.AUTH_USER_MODEL),
        ),
    ]
