# Generated by Django 5.0.4 on 2024-05-15 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('repetitions', models.IntegerField(max_length=100)),
                ('id_exercise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exercise.exercise')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
        ),
    ]
