# Generated by Django 5.0.4 on 2024-05-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='repetitions',
            field=models.IntegerField(),
        ),
    ]
