# Generated by Django 5.0.4 on 2024-05-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_progress_repetitions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
